"""table_2

Revision ID: 06659725a4d0
Revises: 642db47846c4
Create Date: 2021-10-20 00:28:55.081739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06659725a4d0'
down_revision = '642db47846c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_word',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], )
    )
    op.create_table('dictionary_word',
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary.id'], )
    )
    op.drop_table('bookword')
    op.drop_table('dictionaryword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaryword',
    sa.Column('word_id', sa.INTEGER(), nullable=True),
    sa.Column('dictionary_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary.id'], )
    )
    op.create_table('bookword',
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.Column('word_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], )
    )
    op.drop_table('dictionary_word')
    op.drop_table('book_word')
    # ### end Alembic commands ###
