"""table

Revision ID: 642db47846c4
Revises: 
Create Date: 2021-10-18 23:56:57.123875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642db47846c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_text', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_base_text'), 'word', ['base_text'], unique=False)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('input_book_path', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_book_path')
    )
    op.create_index(op.f('ix_book_date_created'), 'book', ['date_created'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=True)
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translate', sa.String(length=120), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_translate'), 'translation', ['translate'], unique=False)
    op.create_table('bookword',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], )
    )
    op.create_table('dictionaryword',
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('dictionary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dictionary_id'], ['word.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary.id'], )
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('base_text', sa.Text(), nullable=True),
    sa.Column('translate_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentence')
    op.drop_table('dictionaryword')
    op.drop_table('bookword')
    op.drop_index(op.f('ix_translation_translate'), table_name='translation')
    op.drop_table('translation')
    op.drop_table('dictionary')
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_date_created'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_word_base_text'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
