"""test_x_5

Revision ID: 94748735a688
Revises: 06659725a4d0
Create Date: 2021-11-10 22:59:51.665878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94748735a688'
down_revision = '06659725a4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_title', table_name='book')
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.create_index('ix_book_title', 'book', ['title'], unique=False)
    # ### end Alembic commands ###
